Repository cms-data/RecoBTag-Combined, pull requests merged in 2020-07, with the labels that each got.

#31 DDXV2
  DeepDoubleX/102X/V02/BvL.h5
  DeepDoubleX/102X/V02/BvL.onnx
  DeepDoubleX/102X/V02/CvB.h5
  DeepDoubleX/102X/V02/CvB.onnx
  DeepDoubleX/102X/V02/CvL.h5
  DeepDoubleX/102X/V02/CvL.onnx
  DeepDoubleX/102X/V02/model_info.txt
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, reconstruction-pending, requires-external, tests-approved

#30 Higgs Interaction Network Tagger Models in ONNX and PyTorch
  HiggsInteractionNet/V00/IN.onnx
  HiggsInteractionNet/V00/IN.pth
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, reconstruction-approved, requires-external, tests-rejected

#33 Add ONNX models of ParticleNet V00
  ParticleNetAK8/General/V00/ParticleNet.onnx
  ParticleNetAK8/General/V00/preprocess.json
  ParticleNetAK8/MD-2prong/V00/ParticleNet.onnx
  ParticleNetAK8/MD-2prong/V00/preprocess.json
Labels: comparison-available, externals-approved, fully-signed, orp-approved, reconstruction-approved, requires-external, tests-approved
